### ISSUE TITLE
Phobos Integration

### ISSUE THREAD

**Issue by burner** [tsbockman/checkedint#1]
How do you feel about pushing this into phobos? Do you think the code and the docs are ready?

**Comment by tsbockman** [comment]
My goal is to formally submit `checkedint` for consideration within the next month or so. I'm not _quite_ ready yet today, though: there are still a few small files that lack documentation.

(Presumably, there will also be a long delay between submission and acceptance.)

Have you tried a recent build? Do you like the new error signalling mechanism?

**Comment by burner** [comment]
sounds like a plan.

good idea to give the user the choice to throw or not to throw. ping me when your done. I will do the review management if you like.

**Comment by tsbockman** [comment]
@burner 

> ping me when your done. I will do the review management if you like.

My official Phobos PR is up now: https://github.com/dlang/phobos/pull/4407

**Comment by tsbockman** [comment]
> In two weeks I will talk to tsbockmann how much time he needs to work in all comments.

@burner When you need to discuss anything with me directly as the review manager, I suggest doing it here. That way people following the forum thread(s) don't get bothered with notifications for messages not addressed to them.

My list of comments that still need to be resolved:

* **JackStouffer** [doesn't like the way that `checkedint.conv.to()` shadows `std.conv.to()`](https://github.com/dlang/phobos/pull/4407#issuecomment-224634537).

I'll update this list as needed, because I want to be able to see everything in one place. You may wish to add your own list below this one, that you can use to point out anything you think I've missed.

**Comment by tsbockman** [comment]
@burner It seems that **andralex**'s opinion is the only one that really counts for Phobos inclusion, and he wants me to rewrite this yet again to add a bunch of new features (and somehow make the code simpler in the process) that I don't think really belong here - or at least don't care about enough to implement.

So, this will just be a DUB package. It's Boost Licensed, so you're welcome to fork it if you want to take a crack at pleasing him.
