### ISSUE TITLE
imports at the module scope should not be selective

### ISSUE THREAD

**Issue by BBasile** [tsbockman/CheckedInt#1]
Because of the a [well known DMD front-end bug](https://issues.dlang.org/show_bug.cgi?id=314), if you specify the symbol to import in a global import, then this symbol will becomes public.

For example if ones imports _future.checkedint_, in a module, these symbols will also be imported:

https://github.com/tsbockman/CheckedInt/blob/master/future.checkedint.d#L12

It's not recommended to use selective global import until this bug gets fixed.

**Comment by tsbockman** [comment]
Thanks, I am aware of that bug. I'm hoping it will be [fixed before `checkedint` is released](https://github.com/D-Programming-Language/dmd/pull/3407#issuecomment-136974686).

If not, I plan to clean up the imports when I do my big reformatting pass, since I have deliberately not followed the [Phobos style guide](http://dlang.org/dstyle.html) while working on this.

I should also mention that the code in this repository is quite out-of-date:
* I decided to significantly change the way that `nothrow` code is supported; it now uses an [IeeeFlags](http://dlang.org/phobos/std_math.html#.IeeeFlags) like mechanism. This is *much* easier to use.
* The `checkedint` package has been split into a hierarchy of sub-packages, with various things renamed to better manage symbol conflicts with other parts of Phobos.
* Template bloat has been reduced.
* It is now pretty fast on all three major compilers (if appropriate options are used), not just GDC (although GDC is still best).
* etc.

The new version is set up as a DUB package, which I hope to upload soon in a fresh repository. I can ping you when it's ready, if you like.

**Comment by tsbockman** [comment]
@BBasile The new version is online now: [checkedint](http://code.dlang.org/packages/checkedint).
